#!/bin/bash

echo "RUST_VERSION=stable" >> $GITHUB_ENV
echo "CMAKE_VERSION=3.27.9" >> $GITHUB_ENV
echo "OPENSSL_VERSION=openssl-3.2.1" >> $GITHUB_ENV
echo "ZIG_VERSION=0.11.0" >> $GITHUB_ENV
echo "LLVM_VERSION=17" >> $GITHUB_ENV
echo "MUSL_VERSION=1.2.4" >> $GITHUB_ENV
