name: Test zig images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            platform: amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Vars
        run: |
          echo "BUILD_DATE=$(date --utc)" >> $GITHUB_ENV
          ./build-args.sh
      - name: Build and push Docker images (pinned)
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./zig/${{ matrix.target }}.Dockerfile
          no-cache: true
          cache-to: type=inline
          # cache-from: type=inline
          pull: true
          push: false
          # load: true
          tags: cross:${{ env.RUST_VERSION }}-${{ matrix.target }}
          build-args: |
            RUST_VERSION=${{ env.RUST_VERSION }}
            CMAKE_VERSION=${{ env.CMAKE_VERSION }}
            OPENSSL_VERSION=${{ env.OPENSSL_VERSION }}
            ZIG_VERSION=${{ env.ZIG_VERSION }}
            LLVM_VERSION=${{ env.LLVM_VERSION }}
            MUSL_VERSION=${{ env.MUSL_VERSION }}
          labels: |
            tech.harmless.experimental.name="ink-cross:${{ matrix.target }}"
            tech.harmless.experimental.pull_request_build="${{ github.event_name == 'pull_request' }}"
            tech.harmless.experimental.run_number="${{ github.run_number }}"
            tech.harmless.experimental.repo="${{ github.repositoryUrl }}"
            org.opencontainers.image.authors="harmless-tech, crow-rest"
          platforms: linux/${{ matrix.platform }}
          builder: ${{ steps.buildx.outputs.name }}
      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: cross-${{ matrix.target }}-${{ matrix.platform }}
          path: /tmp/cross-${{ matrix.target }}-${{ matrix.platform }}.tar
