name: Test images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  nix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerArch: "amd64"
            sysArch: "x86_64-linux"
            sysArchFull: "x86_64-unknown-linux-gnu"
            crossArch: "aarch64-unknown-linux-musl"
          - dockerArch: "amd64"
            sysArch: "x86_64-linux"
            sysArchFull: "x86_64-unknown-linux-gnu"
            crossArch: "x86_64-unknown-linux-musl"
          - dockerArch: "arm64"
            sysArch: "aarch64-linux"
            sysArchFull: "aarch64-unknown-linux-gnu"
            crossArch: "aarch64-unknown-linux-musl"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          install_url: https://releases.nixos.org/nix/nix-2.19.0/install
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          nix-build nix/cross-image.nix -A cross \
            --argstr dockerArch ${{ matrix.dockerArch }} \
            --argstr sysArch ${{ matrix.sysArch }} \
            --argstr sysArchFull ${{ matrix.sysArchFull }} \
            --argstr crossArch ${{ matrix.crossArch }}
      - run: docker load < result
      - run: docker images
      - uses: actions/upload-artifact@v3
        with:
          name: image---${{ matrix.sysArchFull }}---${{ matrix.crossArch }}
          path: result
